// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_consumer.Api.Reserva.Repository;

#nullable disable

namespace api_consumer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230418002359_Main")]
    partial class Main
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_consumer.Api.Reserva.Entity.ReservaEntity", b =>
                {
                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEstacionamento")
                        .HasColumnType("integer")
                        .HasColumnName("id_estacionamento");

                    b.Property<int>("Duracao")
                        .HasColumnType("integer")
                        .HasColumnName("duracao");

                    b.Property<DateTime>("HorarioReserva")
                        .HasColumnType("timestamp")
                        .HasColumnName("horario_reserva");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_veiculo");

                    b.HasKey("IdCliente", "IdEstacionamento");

                    b.ToTable("reserva");
                });
#pragma warning restore 612, 618
        }
    }
}
