version: '3.8'
name: why_park
services:
  mysql_why:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3303:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpass
      MYSQL_USER: usr_whypark
      MYSQL_PASSWORD: mysecretpass
      MYSQL_DATABASE: DB_WHYPARK
    cap_add:
      - SYS_NICE
    networks:
      - mysql_why-networks
    volumes:
      - mysql_why-db-data:/var/lib/mysql
  redis_whypk:
    image: redis
    container_name: redis_whypk
    command: redis-server --save 20 1 --loglevel warning  --requirepass password123
    ports:
      - "6379:6379"
    volumes:
      - /local-data/:/data redis/redis-stack:latest
    environment:
      - REDIS_PASSWORD = password123
volumes:
  mysql_why-db-data:
  redis:
networks:
  mysql_why-networks:
    driver: bridge
  redis_whypk:
    driver: bridge
